app:
  listen: 
    host: 0.0.0.0
  baseUrl: http://backstage.home
backend:
  baseUrl: http://backstage.home
  listen:
    port: 7007
    host: 0.0.0.0
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

organization:
  name: Jay's Organization

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

catalog:
  rules:
    - allow: [User, Group, Component, System, API, Resource, Location]
  locations:
    - type: file
      target: /app/entities/users.yaml
      rules:
        - allow: [User]
    - type: file
      target: /app/entities/groups.yaml
      rules:
        - allow: [Group]
    - type: github-discovery
      target: https://github.com/jaysuzi5/backstage-software-templates
      rules:
        - allow: [Template]        

techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
